export const siteConfig = {
  name: "The Terminal",
  title: "The Terminal - Your Personal Operating System",
  description:
    "The Terminal is an open-source, self-hostable personal operating system for tasks, notes, journals, habits, finances, calendar planning, and reflections.",
  author: "whoisbeet",
  repositoryUrl: "https://github.com/whoisbeet/life-os",
  ogImage:
    "https://raw.githubusercontent.com/whoisbeet/life-os/main/public/screenshots/landing.jpg",
  screenshotUrls: [
    "https://raw.githubusercontent.com/whoisbeet/life-os/main/public/screenshots/landing.jpg",
    "https://raw.githubusercontent.com/whoisbeet/life-os/main/public/screenshots/dashboard.jpeg",
    "https://raw.githubusercontent.com/whoisbeet/life-os/main/public/screenshots/brain-graph.jpeg",
    "https://raw.githubusercontent.com/whoisbeet/life-os/main/public/screenshots/insight.jpeg",
  ],
  keywords: [
    "The Terminal",
    "personal operating system",
    "digital brain",
    "second brain",
    "open source productivity",
    "personal knowledge management",
    "knowledge graph",
    "habit tracker",
    "journal app",
    "calendar planner",
    "task manager",
    "goal tracker",
    "focus timer",
    "finance tracker",
    "personal dashboard",
    "productivity dashboard",
    "Next.js productivity app",
    "PWA productivity",
  ],
};
