"use client";
import { useLifeOS } from "@/store/life-os";
import { useStats, useInbox } from "@/lib/hooks";
import { Icon } from "./icon";
import { DOMAINS } from "@/lib/constants";
import { cn } from "@/lib/utils";
import { ScrollArea } from "@/components/ui/scroll-area";
import { motion } from "framer-motion";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useState } from "react";

const NAV = [
  { key: "dashboard", name: "Dashboard", icon: "LayoutDashboard" }, { key: "inbox", name: "Inbox", icon: "Inbox" }, { key: "calendar", name: "Calendar", icon: "CalendarDays" }, { key: "agenda", name: "Agenda", icon: "CalendarRange" }, { key: "focus", name: "Focus", icon: "Brain" }, { key: "projects", name: "Projects", icon: "FolderKanban" }, { key: "graph", name: "Brain Graph", icon: "Network" }, { key: "reviews", name: "Reviews", icon: "NotebookPen" }, { key: "insights", name: "Insights", icon: "TrendingUp" }, { key: "all", name: "All Items", icon: "Layers" },
] as const;

function SidebarContent({ onNavigate }: { onNavigate?: () => void }) {
  const { view, setView } = useLifeOS(); const { data: stats } = useStats(); const { data: inbox } = useInbox(); const inboxCount = stats?.inboxCount ?? inbox?.items?.length ?? 0;
  function nav(key: any) { setView(key); onNavigate?.(); }
  return (<>
    <div className="flex h-14 flex-shrink-0 items-center gap-2.5 border-b border-zinc-800/80 px-4"><div className="flex h-8 w-8 items-center justify-center rounded-md border border-zinc-700 bg-zinc-900 font-mono text-sm text-zinc-100">&gt;_</div><div><div className="font-mono text-sm font-semibold leading-none tracking-tight text-zinc-100">The Terminal</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.18em] text-zinc-500">Personal OS</div></div></div>
    <ScrollArea className="flex-1 px-3 py-3"><div className="space-y-0.5">{NAV.map((n) => { const active = view === n.key; const badge = n.key === "inbox" && inboxCount > 0 ? inboxCount : null; return <button key={n.key} onClick={() => nav(n.key)} className={cn("group relative flex w-full items-center gap-3 rounded-md border border-transparent px-3 py-2 font-mono text-xs transition-all", active ? "border-zinc-800 bg-zinc-900 text-zinc-100" : "text-zinc-500 hover:bg-zinc-900/70 hover:text-zinc-200")}>{active && <motion.span layoutId="nav-active" className="absolute left-0 top-1/2 h-4 w-0.5 -translate-y-1/2 rounded-r-full bg-zinc-100" />}<Icon name={n.icon} className="h-4 w-4" /><span className="flex-1 text-left">{n.name}</span>{badge && <span className="rounded border border-zinc-700 px-1.5 py-0.5 text-[10px] text-zinc-300">{badge}</span>}</button>; })}</div><div className="mb-2 mt-5 px-3 font-mono text-[9px] font-semibold uppercase tracking-[0.18em] text-zinc-600">Life Domains</div><div className="space-y-0.5">{DOMAINS.map((d) => { const active = view === d.key; const count = stats?.byDomain?.find((b: any) => b.domain === d.key)?.count; return <button key={d.key} onClick={() => nav(d.key)} className={cn("group flex w-full items-center gap-3 rounded-md border border-transparent px-3 py-1.5 text-xs transition-all", active ? "border-zinc-800 bg-zinc-900 text-zinc-100" : "text-zinc-500 hover:bg-zinc-900/70 hover:text-zinc-200")}><span className="flex h-5 w-5 items-center justify-center rounded border border-zinc-800 bg-zinc-950" style={{ color: d.color }}><Icon name={d.icon} className="h-3 w-3" /></span><span className="flex-1 text-left font-mono">{d.short}</span>{count ? <span className="font-mono text-[10px] text-zinc-600">{count}</span> : null}</button>; })}</div></ScrollArea>
    <div className="flex-shrink-0 border-t border-zinc-800/80 p-2"><button onClick={() => nav("settings")} className={cn("flex w-full items-center gap-2 rounded-md border border-transparent px-3 py-1.5 font-mono text-xs transition-colors", view === "settings" ? "border-zinc-800 bg-zinc-900 text-zinc-100" : "text-zinc-500 hover:bg-zinc-900/70 hover:text-zinc-200")}><Icon name="Settings" className="h-3.5 w-3.5" />Settings</button><button onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }} className="flex w-full items-center gap-2 rounded-md px-3 py-1.5 font-mono text-xs text-zinc-500 transition-colors hover:bg-rose-950/30 hover:text-rose-400"><Icon name="LogOut" className="h-3.5 w-3.5" />Sign out</button></div>
  </>);
}
export function Sidebar() { const [mobileOpen, setMobileOpen] = useState(false); const closeMobile = () => setMobileOpen(false); return (<><aside className="hidden h-full w-60 flex-col border-r border-zinc-800/80 bg-zinc-950 md:flex"><SidebarContent /></aside><button onClick={() => setMobileOpen(true)} className="fixed left-3 top-3 z-40 flex h-10 w-10 items-center justify-center rounded-md border border-zinc-800 bg-zinc-950/90 text-zinc-300 shadow-md backdrop-blur-md md:hidden" aria-label="Open menu"><Icon name="Menu" className="h-5 w-5" /></button><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetContent side="left" className="w-72 border-zinc-800 bg-zinc-950 p-0"><SheetHeader className="sr-only"><SheetTitle>Navigation</SheetTitle></SheetHeader><div className="flex h-full flex-col"><SidebarContent onNavigate={closeMobile} /></div></SheetContent></Sheet></>); }
